version: '1.2'

services: 

    postgres_data:
        image: postgres:15
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "bd_jdea", "-U"]
            interval: 10s
            timeout: 45s
            retries: 10
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=bd_jdea
            - APP_DB_USER=docker
            - APP_DB_PASS=docker
            - APP_DB_NAME=docker
        volumes:
            - /tmp/database:/var/lib/postgresql_uniesp/data
        ports:
            - 5432:5432